services:
  mp-app:
    build:
      target: prod
    container_name: macva-press
    env_file:
      - .env
    restart: always
    depends_on:
      - mp-db
      - mp-redis
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./static/ads:/app/static/ads

  mp-db:
    image: ${DB_DRIVER}:latest
    restart: always
    container_name: macva-press-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mp-redis:
    image: redis:latest
    container_name: macva-press-redis
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --maxmemory 100mb 
      --maxmemory-policy allkeys-lru 
      --activedefrag yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: macva-press-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mp-app
    environment:
      - TZ=Europe/Belgrade

  duckdns:
    image: linuxserver/duckdns
    container_name: macva-press-duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
      - SUBDOMAINS=macva-press
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:
  static_uploads:


# docker compose -f docker-compose-prod.yml up --build -d

